import {
  Inter,
  Questrial,
  Rubik_Mono_One,
  Unbounded,
  Poppins,
} from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const unbounded = Unbounded({ 
  subsets: ["latin"],
  variable: "--font-unbounded"
});
const questrial = Questrial({ 
  subsets: ["latin"], 
  weight: ["400"],
  variable: "--font-questrial"
});
const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter"
});
const rubik_mono_one = Rubik_Mono_One({ 
  subsets: ["latin"], 
  weight: ["400"],
  variable: "--font-rubik"
});
const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Mood4Movie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={clsx(
          unbounded.variable,
          questrial.variable,
          inter.variable,
          rubik_mono_one.variable,
          poppins.variable,
          'font-sans',
          'wrapper',
          'flex',
          'flex-col'
        )}
      >
        {children}
      </body>
    </html>
  );
}